# Generated by Django 3.1 on 2021-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productNum', models.CharField(max_length=100)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('casePrice', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('quantity', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(height_field=450, upload_to='ProductImages/', width_field=450)),
                ('parentGroup', models.CharField(max_length=100)),
                ('subParentGroup', models.CharField(max_length=100)),
                ('productCategory', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-parentGroup', '-subParentGroup', '-productCategory'],
            },
        ),
    ]
