# Generated by Django 3.1 on 2021-10-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211021_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/media/ProductImages/'),
        ),
    ]
