# Generated by Django 3.1 on 2021-10-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211021_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subParentProductCategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
